# Generated by Django 4.2.6 on 2023-10-07 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer_tb',
        ),
    ]
