# Generated by Django 4.2.6 on 2023-11-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart_tb',
        ),
    ]
