# Generated by Django 4.2.6 on 2023-11-24 13:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
        ('customer', '0003_alter_cart_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_id', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('payment_status', models.BooleanField(default=False)),
                ('payment_id', models.CharField(max_length=25, null=True, unique=True)),
                ('signature_id', models.CharField(max_length=25, null=True, unique=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
            options={
                'db_table': 'order_tb',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Order placed', max_length=100)),
                ('packed_date', models.DateField(default=datetime.date.today, null=True)),
                ('cancelled_date', models.DateField(default=datetime.date.today, null=True)),
                ('delivery_date', models.DateField(default=datetime.date.today, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.product')),
            ],
            options={
                'db_table': 'orderitem_tb',
            },
        ),
    ]
