# Generated by Django 4.2.6 on 2023-11-28 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=1, max_length=25, unique=True),
        ),
    ]
