# Generated by Django 4.2.6 on 2023-11-02 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_seller'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(max_length=20)),
                ('product_name', models.CharField(max_length=50)),
                ('product_category', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('price', models.FloatField()),
                ('image', models.ImageField(upload_to='product/')),
                ('status', models.CharField(default='available', max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.seller')),
            ],
            options={
                'db_table': 'product_tb',
            },
        ),
    ]
